version: '3.9'
services:
  db:
    container_name: pgsql-db
    image: postgres
    hostname: pgsql-db
    ports:
      - '5432:5432'
    volumes:
      - 'pgsqldata:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P4$$$$w0rd
      POSTGRES_DB: StockSolution
    restart: unless-stopped

volumes:
  pgsqldata:
